# Generated by Django 3.2.14 on 2022-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetContactTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetMessageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenueMessage', models.CharField(max_length=1000)),
                ('auteur', models.CharField(max_length=100)),
                ('destinataire', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
